name: test Nico Build.
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: mise_en_ligne
        run: echo "Je suis en dev"